# Generated by Django 5.2.8 on 2025-11-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='source',
            field=models.CharField(choices=[('chat', 'Chat'), ('telegram', 'Telegram'), ('api', 'API'), ('ukweli', 'Ukweli')], max_length=20),
        ),
    ]
