# """Django settings for safeAi project.

# Generated by 'django-admin startproject' using Django 5.1.1.
# """

# import os
# from pathlib import Path
# from dotenv import load_dotenv
# import dj_database_url


# BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(BASE_DIR.parent / ".env")

# STATIC_URL = '/static/'

# # REQUIRED for Render
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# # Quick-start development settings - unsuitable for production
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ.get(
#     "SECRET_KEY",
#     "django-insecure-@=+7-a5f@x4(%sqa68h+jxxod2r4fv!n_86as3wt0e^xiheoie",
# )

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

# ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")


# # Application definition

# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     "rest_framework",
#     "drf_spectacular",
#     "corsheaders",
#     "chat",
# ]

# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "corsheaders.middleware.CorsMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# ROOT_URLCONF = 'safeAi.urls'

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.debug",
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "safeAi.wsgi.application"


# # Database

# # DATABASES = {
# #     "default": {
# #         "ENGINE": "django.db.backends.postgresql",
# #         "NAME": os.environ.get("DB_NAME", ""),
# #         "USER": os.environ.get("DB_USER", "postgres"),
# #         "PASSWORD": os.environ.get("DB_PASSWORD", ""),
# #         "HOST": os.environ.get("DB_HOST", "localhost"),
# #         "PORT": os.environ.get("DB_PORT", "5432"),
# #     }
# # }

# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.environ.get("DATABASE_URL")
#     )
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)

# STATIC_URL = "static/"

# # CORS

# cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if os.environ.get("CORS_ALLOWED_ORIGINS") else []
# CORS_ALLOWED_ORIGINS = [origin for origin in cors_origins if origin]


# # Default primary key field type

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REST_FRAMEWORK = {
#     "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
# }


# SPECTACULAR_SETTINGS = {
#     "TITLE": "SAFEAI API",
#     "DESCRIPTION": "API documentation for SAFEAI backend",
#     "VERSION": "1.0.0",
# }

# CSRF_TRUSTED_ORIGINS = [
#     # "http://localhost:3000",
#     # "http://127.0.0.1:3000",
#     "https://ukweli-lens-frontend.onrender.com",

# ]



"""
Django settings for safeAi project.
Generated by 'django-admin startproject' using Django 5.1.1.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR.parent / ".env")

# ================================
# STATIC FILES (REQUIRED FOR RENDER)
# ================================
STATIC_URL = "/static/"

# Where collectstatic will put files (REQUIRED)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Only needed if you actually have a local static/ folder in your project
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ================================
# SECURITY SETTINGS
# ================================
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-@=+7-a5f@x4(%sqa68h+jxxod2r4fv!n_86as3wt0e^xiheoie",
)

DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = ["ukweli-lens.onrender.com", "127.0.0.1", "localhost"]

# ================================
# APPLICATIONS
# ================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "chat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "safeAi.urls"

# ================================
# TEMPLATES
# ================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "safeAi.wsgi.application"

# ================================
# DATABASE (Render → PostgreSQL)
# ================================


# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ.get("DB_NAME", ""),
#         "USER": os.environ.get("DB_USER", "postgres"),
#         "PASSWORD": os.environ.get("DB_PASSWORD", ""),
#         "HOST": os.environ.get("DB_HOST", "localhost"),
#         "PORT": os.environ.get("DB_PORT", "5432"),
#     }
# }
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL")
    )
}

# ================================
# PASSWORD VALIDATION
# ================================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ================================
# INTERNATIONALIZATION
# ================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ================================
# CORS
# ================================
cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") \
    if os.environ.get("CORS_ALLOWED_ORIGINS") else []

CORS_ALLOWED_ORIGINS = [origin for origin in cors_origins if origin]

# ================================
# PRIMARY KEY
# ================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ================================
# DRF + OPENAPI
# ================================
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "SAFEAI API",
    "DESCRIPTION": "API documentation for SAFEAI backend",
    "VERSION": "1.0.0",
}

# ================================
# CSRF
# ================================
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://ukweli-lens-frontend.onrender.com",
]


cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") \
    if os.environ.get("CORS_ALLOWED_ORIGINS") else []

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "https://ukweli-lens-frontend.onrender.com",
    *[origin for origin in cors_origins if origin],
]